// ---------------------------------------------------------------------------
// Gallery grid. Builds a square-tile grid from the render manifest; clicking a
// tile opens the shared fullscreen lightbox (see lightbox.js). Missing image
// files fall back to a numbered placeholder so the page is reviewable before
// the renders land.
// ---------------------------------------------------------------------------
import { RENDERS } from './renders.js';
import { createLightbox } from './lightbox.js';

const grid = document.getElementById('grid');

// The grid loads a square thumbnail beside each full-size render:
// renders/foo.jpg → renders/thumb/foo.jpg (generated by ./make-thumbs.sh).
function thumbFor(render) {
  return render.thumb ?? render.src.replace(/^renders\//, 'renders/thumb/');
}

// Inline SVG placeholder (data URI) shown when a render file is absent.
function placeholder(label) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600">
    <rect width="100%" height="100%" fill="#0b0e16"/>
    <rect x="8" y="8" width="584" height="584" fill="none" stroke="#2a3550" stroke-width="2"/>
    <text x="50%" y="50%" font-family="Helvetica,Arial" font-size="48"
      fill="#56627d" text-anchor="middle" dominant-baseline="middle">${label}</text>
  </svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

// The lightbox shows full-size renders, falling back to the numbered placeholder
// if an original is missing.
const { open } = createLightbox(RENDERS, {
  onMissing: (idx) => placeholder(String(idx + 1).padStart(2, '0')),
});

RENDERS.forEach((render, idx) => {
  const button = document.createElement('button');
  button.className = 'tile';
  button.type = 'button';
  button.setAttribute('aria-label', `Open ${render.alt}`);

  // Grid fallback chain: thumbnail → full-size render → numbered placeholder.
  // So tiles still appear if thumbs haven't been generated yet (just heavier).
  const img = document.createElement('img');
  img.loading = 'lazy';
  img.alt = render.alt;
  img.src = thumbFor(render);
  let stage = 'thumb';
  img.addEventListener('error', () => {
    if (stage === 'thumb') { stage = 'full'; img.src = render.src; }
    else if (stage === 'full') { stage = 'placeholder'; img.src = placeholder(String(idx + 1).padStart(2, '0')); }
  });

  button.appendChild(img);
  button.addEventListener('click', () => open(idx));
  grid.appendChild(button);
});
